services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/app